#!/bin/sh

#used to delete the database

. ./head.sh

#rm -f "$dbase"

if [ -z "$dbase" ]; then
        echo "hey, \$dbase is empty! halting"
        exit 3
fi
#sudo -u postgres dropdb -U demlinks_user "$dbase"
#sudo -u postgres createdb -U demlinks_user "$dbase"
sudo ./initdb.sh

