#!/bin/sh
src="main.php"
dbase="demlinks6.3sql"
src2="dmlDBL0.php"
src3="dmlDBL1.php"

#append=".cpphead.php"
#prepend="autogenerated."
#cppparams="-E -x c++"

#phpfile="${prepend}${src}.safety${append}"

run()
{
        local src="$1"
#        local tmpphpfile="${prepend}${src}.safety${append}"
#        echo "<?php" >"$tmpphpfile"
#        cpp $cppparams "$src">>"$tmpphpfile"
#        if [ "$?" -eq "0" ]; then
                        time -p php "$src"
#        fi
}
