#!/bin/sh

#for OpenBSD (at least)
export AUTOMAKE_VERSION=1.9
export AUTOCONF_VERSION=2.59
#the following is for using gmake on BSDs and for linuxes w/o gmake link pointing to make
type gmake >/dev/null 2>&1
if [ "$?" -ne "0" ]; then
        gmake=make
else
        gmake=gmake
fi
(cd "`pwd`/obj/" 2>&1 >/dev/null && $gmake clean 2>&1 >/dev/null)
$gmake -f Makefile.svn || exit $?

doexe () {
        chmod +x "$1"
}
alias doexec=doexe

dolink () {
        local src="$1"
        local dest="$2"
        if [ -z "$dest" ]; then
                dest="$src"
        else
                src="$dest"
                dest="$1"
        fi
        ln -s "../$src" "./src/$dest" >/dev/null 2>&1
}

do_ () {
cat >"$1" <<EOF
echo "--------------------START--------------------------------------"
#autogenerated by $0 on `date`
cd "`pwd`/obj/src/" && pwd && make $2 && clear && if [ "\$TERM" != "linux" ]; then "./$2" ; if [ "\$?" -eq "134" ]; then sudo "./$2" ; fi ; else sudo "./$2" ; fi
EOF
doexe "$1"
dolink "$1"
}

#shortcut links to executables
do_ 1 dml_imagine
do_ 2 setup_inputs

zvim() {
        local outf="$1"
cat >"$outf" <<EOF
#!/bin/sh
#a wrapper for 'vim' to be able to edit the file from <any current dir (aka pwd) *ahem* that has this script in it>
cd "`pwd`/src" && ./cs #refreshing cscope dbase, just in case
cd "`pwd`/obj/src" && vim "\$@"
EOF
        doexe "$outf"
        dolink "$outf"
}
zvim zvim

# <cscope & vim> smacking

cscope () {
        local outf="`pwd`/src/cs"
cat >"$outf" <<EOF
#!/bin/sh
#autogenerated by $0 on `date`
find . -name '*.cpp' -o -name '*.h' > cscope.files
cscope -b
EOF
        doexe "$outf"
}

cscope

./vimaddon.sh

# search script smacking

dolink "s"
pwd
dolink "si" "s"

echo -e '\033[37m...or you may want run "\033[32m./1\033[37m" OR "\033[32m./2\033[37m" anytime u modify some src files - this will compile and run the specific demlinks exe programs'
echo -e 'Also, "\033[32m./s \033[34m<\033[35mtext pattern with spaces\033[34m>\033[37m" will recursively search starting from current dir all important files for "text pattern with spaces" and show a menu with results (do not include the \033[34m<\033[37m and \033[34m>\033[37m with pattern)'
echo -e '\033[32m./src/cs\033[37m" a script used to manually refresh the cscope database (apparently necessary when source files get modified)'
echo -e '\033[34m./zvim\033[37m is to be used only by copy pasting the line from the reported errors after running one of ./1 or ./2" ie. a line like this "./zvim ../../src/main.cpp +57"\033[37m'





