#!/bin/bash
#search script that uses whiptail and vim to show and respectively edit the files in which <the passed parameters as pattern> are found
#(c) AtKaaZ 25aug2006 released under GNU GPL
#ie. "./s TDMLPointer" will recursively search all files(except some see --exclude below) and display a menu with all results where pressing enter on an item will position you on that line in the file with vim.
#ie. "./s \<main\>" will search for whole word "main" only
thething="vim "
#FIXME: need to suppress tabs!
#menu=`grep -n -R -e "$*" * | awk 'BEGIN{FS=":";} { printf("\"vim "$1" +"$2"\" \""$0"\" ");}'`
#menu="$( grep -n -R -e "$*" * | awk 'BEGIN{FS=":";} { printf("vim %s +%s~%s~",$1,$2,$0);}' )"
if [ "${0##*/}" == "si" ]; then
        mi="-i"
else
        unset mi
fi
export GREP_OPTIONS="--binary-files=without-match --exclude=\*\.svn\* --exclude=cscope.\* --exclude=s"
menu="$( grep $mi -n -R -e "$*" * | awk 'BEGIN{FS=":";} { printf("'"$thething"'%s +%s\" %s ",$1,$2,substr($0,1+length($1 FS $2 FS)));}' )"
#menu="${menu//\)/ }"
#menu="${menu//\(/ }"
#menu="$( grep -n -R -e "$*" * )"
#grep -n -R -e "$*" *
#| awk 'BEGIN{FS=":";} { printf("\"vim %s +%s\" \"%s\" ",$1,$2,$0);}' )"
#echo $menu
#exit
declare -a menua
count=0
while [ -n "$menu" ]; do
        last="${menu#$thething*\"}"
        len=$(( ${#menu} - ${#last} ))
        if [ "$len" -gt "0" ]; then
                len=$(( $len - 1 ))
        else
                len=0
        fi
        first=${menu:0:$len}
#        echo "$first (first)"
#        echo
        menua+=("$first")
        menu="$last"
#        echo "$menu (menu)"
#        echo
        last="${menu#*$thething}"
        if [ -n "$last" ]; then
                last="${thething}$last"
        fi
        len=$(( ${#menu} - ${#last} ))
        if [ "$len" -gt "0" ]; then
                len=$(( $len - 1 ))
        else
                len=${#menu}
                last=""
        fi
        second=${menu:0:$len}
        menua+=("$second")
#        echo "$second (second)"
#        echo
        menu="$last"
#        echo "$last (last)"
        #exit
        count=$(( $count + 1 ))
done
#a() {
#        echo "$@"
#        #echo "$*"
#        echo "$#"
#}
#a "${menua[@]}"
if [ "${#menua[@]}" -le "0" ]; then
        echo "No results."
        exit 1
fi
#whiptail --output-fd 2 --menu "grep results" 0 0 5 -- "${menua[@]}"
#exit
randfifo="/tmp/s_grep$RANDOM"
#mkfifo $randfifo
defitem="0"
while [ -z "$QUIT" ]; do
whiptail --default-item "$defitem" --output-fd 2 --menu "grep results $count" 0 0 5 -- "${menua[@]}" 2>"$randfifo"
exitcode="$?"
selected="`cat $randfifo`"
if [ -n "$selected" -a "$exitcode" -eq "0" ]; then
        $selected
        defitem="$selected"
else
        if [ -n "$selected" ]; then
                echo "ERROR: $selected"
        fi
        QUIT=1
fi
done
rm -f "$randfifo"
clear
#echo $defitem
