#!/bin/sh

#used to execute main file

. ./head.sh

#rm -f "$dbase"

echo "<?php" >"$phpfile"
cpp $cppparams "$src">>"$phpfile"
if [ "$?" -eq "0" ]; then
        time -p -- php "$phpfile"
#-B "<?php"
fi

