#!/bin/sh
src="main.php"
src2="dmlphpL0.php"
src3="dmlphpL1.php"
dbase="demlinks6.3sql"
append=".cpphead.php"
prepend="autogenerated."
cppparams="-E -x c++"

phpfile="${prepend}${src}.safety${append}"


cpphp()
{
        local src="$1"
        local tmpphpfile="${prepend}${src}.safety${append}"
        echo "<?php" >"$tmpphpfile"
        cpp $cppparams "$src">>"$tmpphpfile"
        if [ "$?" -eq "0" ]; then
                        time -p php "$tmpphpfile"
        fi
}
